### ISSUE TITLE
Failed to create pt_BR exception during FB registration

### ISSUE THREAD

**Issue by bart-at-mobicage** [our-city-app/mobicage-backend#117]
```
2018-09-14 09:41:08.204 CEST
Failed to build facebook profile
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/jobs-no-sync.412561209551439336/rogerthat/pages/register_mobile.py", line 466, in post
    profile = get_profile_for_facebook_user(access_token, None, True, language=language, app_id=app_id)
  File "/base/data/home/apps/e~rogerthat-server/jobs-no-sync.412561209551439336/mcfw/rpc.py", line 167, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/jobs-no-sync.412561209551439336/mcfw/rpc.py", line 145, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/jobs-no-sync.412561209551439336/rogerthat/bizz/profile.py", line 339, in get_profile_for_facebook_user
    localize(language, 'There is no e-mail address configured in your facebook account. Please use the e-mail based login.'))
FailedToBuildFacebookProfileException: N\xe3o h\xe1 um endere\xe7o de e-mail configurado na sua conta do Facebook. Use o e-mail para fazer o login.

2018-09-14 09:41:08.208 CEST
'ascii' codec can't encode character u'\xe3' in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1511, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1505, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1253, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 1077, in __call__
    return handler.dispatch()
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 547, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/e416f9a06334486a/python27/python27_lib/versions/third_party/webapp2-2.3/webapp2.py", line 545, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/jobs-no-sync.412561209551439336/rogerthat/pages/register_mobile.py", line 470, in post
    description="ERROR: Failed to build facebook profile: %s" % fe))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe3' in position 1: ordinal not in range(128)
```

**Comment by bart-at-mobicage** [comment]
Same for FR:

```
Failed to build facebook profile
Traceback (most recent call last):
  File "/base/data/home/apps/e~rogerthat-server/20181005t153019.413054057188601854/rogerthat/pages/register_mobile.py", line 466, in post
    profile = get_profile_for_facebook_user(access_token, None, True, language=language, app_id=app_id)
  File "/base/data/home/apps/e~rogerthat-server/20181005t153019.413054057188601854/mcfw/rpc.py", line 167, in typechecked_return
    result = f(*args, **kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20181005t153019.413054057188601854/mcfw/rpc.py", line 145, in typechecked_f
    return f(**kwargs)
  File "/base/data/home/apps/e~rogerthat-server/20181005t153019.413054057188601854/rogerthat/bizz/profile.py", line 339, in get_profile_for_facebook_user
    localize(language, 'There is no e-mail address configured in your facebook account. Please use the e-mail based login.'))
FailedToBuildFacebookProfileException: Il n'y a aucune adresse email configur\xe9e dans votre compte facebook ou vous n'avez pas donn\xe9 les autorisations pour acc\xe9der \xe0 votre email. Merci de choisir la connexion via email.
```
